### ISSUE TITLE
[Bug] rplt.errorbar: emptybins=False & xderr = None

### ISSUE THREAD

**Issue by kreczko** [rootpy/rootpy#638]
Dear all,

I have encountered a bug when trying to make matplotlib (via rootpy) to produce legends for markers without the horizontal errors. For this I am setting ```xerr = None``` which works for both rootpy and matplotlib.
However, in combination with emptybins=False I get the error
```python
Traceback (most recent call last):
  File "examples/matplotlib_legend_manip.py", line 28, in <module>
    xerr = None, fmt = "s", label = "rootpy" )
  File "/storage/Workspace/Analysis/DailyPythonScripts/external/rootpy/rootpy/plotting/root2matplotlib.py", line 553, in errorbar
    axes=axes, emptybins=emptybins, **kwargs)
  File "/storage/Workspace/Analysis/DailyPythonScripts/external/rootpy/rootpy/plotting/root2matplotlib.py", line 592, in _errorbar
    xerr = xerr[:, nonempty]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The reason for this is https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/root2matplotlib.py#L591.
```python
if xerr is not False:
    xerr = xerr[:, nonempty]
```
```  xerr is not False ``` returns ```True``` for ```xerr = None```and tries to access it.

The fix is simple and will be supplied shortly. This issue is mainly for reference in the commit.

**Comment by ndawe** [comment]
Fixed in #639
