### ISSUE TITLE
MemoryError in root2hdf5

### ISSUE THREAD

**Issue by qbuat** [rootpy/rootpy#667]
Dear rootpy/root_numpy developers,

I'm experience an issue with ```root2hdf5```

```
root2hdf5 --update -d --complib lzo hhskim.root --complevel 0 hhskim.root
```
gives me:

```bash
INFO:rootpy.root2hdf5] Converting tree 'PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad' with 14386982 entries ...
Traceback (most recent call last):
  File "/afs/cern.ch/user/q/qbuat/public/hhana_install/virtualenv-1.9/atlasVE/lib/python2.7/site-packages/rootpy-0.8.0.dev0-py2.7.egg/rootpy/root2hdf5.py", line 433, in main
    ignore_exception=args.ignore_exception)
  File "/afs/cern.ch/user/q/qbuat/public/hhana_install/virtualenv-1.9/atlasVE/lib/python2.7/site-packages/rootpy-0.8.0.dev0-py2.7.egg/rootpy/root2hdf5.py", line 294, in root2hdf5
    show_progress=show_progress)
  File "/afs/cern.ch/user/q/qbuat/public/hhana_install/virtualenv-1.9/atlasVE/lib/python2.7/site-packages/rootpy-0.8.0.dev0-py2.7.egg/rootpy/root2hdf5.py", line 164, in tree2hdf5
    stop=start + entries)
  File "/afs/cern.ch/user/q/qbuat/public/hhana_install/virtualenv-1.9/atlasVE/lib/python2.7/site-packages/root_numpy-4.3.0.dev0-py2.7-linux-x86_64.egg/root_numpy/_tree.py", line 332, in tree2rec
    weight_name=weight_name).view(np.recarray)
  File "/afs/cern.ch/user/q/qbuat/public/hhana_install/virtualenv-1.9/atlasVE/lib/python2.7/site-packages/root_numpy-4.3.0.dev0-py2.7-linux-x86_64.egg/root_numpy/_tree.py", line 296, in tree2array
    weight_name)
  File "tree.pyx", line 367, in _librootnumpy.root2array_fromCObj (root_numpy/src/_librootnumpy.cpp:367)
  File "tree.pyx", line 297, in _librootnumpy.tree2array (root_numpy/src/_librootnumpy.cpp:297)
MemoryError
ERROR:rootpy.root2hdf5]
```

The tree I'm trying to convert is relatively big (14M entries), so I wonder if there is a limitation on the size of the input tree ?

I'm running with ```root_numpy 4.3.0``` and ```rootpy 0.8.0```.
Thanks in advance!

Cheers,
Quentin

**Comment by ndawe** [comment]
Thanks for reporting! Does it always give a MemoryError at the same point? If you put that large tree somewhere "public" on lxplus, I'll use it to help debug this.

**Comment by qbuat** [comment]
As far as I can tell, yes. I'm converting a file containing 15 trees and it always return a MemoryError when processing this specific tree.

The file is on lxplus here: 
```
/afs/cern.ch/user/q/qbuat/work/public/xtau_output/hadhad/v1/hhskim/hhskim.root
```

Thanks a lot!
Quentin

**Comment by ndawe** [comment]
Back online. I think the tree might be corrupt. I'm anyway seeing lots of errors when cloning the tree into a new file. More info soon...

**Comment by ndawe** [comment]
The tree is too big to fit in memory (>20G?) but the default chunked read of 100k entries should fit. The problem is that root_numpy allocates the full empty array:

https://github.com/rootpy/root_numpy/blob/4.3.0/root_numpy/src/tree.pyx#L297

**Comment by ndawe** [comment]
```
arr = np.empty(num_entries, dtype=dtype)
```

num_entries should reflect the actual number of entries in the slice:

```
slice(start, stop, step).indices(num_entries)
```

I'll fix this.

**Comment by ndawe** [comment]
rootpy/root_numpy#210 should fix this. Can install the head of root_numpy and try running root2hdf5 again?

**Comment by ndawe** [comment]
Yup, I can convert the tree now. I'll leave this issue open until you confirm.

**Comment by ndawe** [comment]
I'll also release root_numpy 4.3.1

**Comment by qbuat** [comment]
I installed the head of root_numpy and created the .h5 file without any problems.
Thanks for investigating and fixing this!
