### ISSUE TITLE
Class RunStopper implemented twice

### ISSUE THREAD

**Issue by lmohrmann** [rootpy/rootpy#683]
Hello,

I have installed ROOT 5.34/34 and rootpy 0.8.1.

When I do `import rootpy`, I get the following errors and then a segfault:
```
bjc[80807]: Class RunStopper is implemented in both /Users/larsm/Software/root_v5.34.34_build/lib/libCore.so and /usr/local/lib/libCore.so. One of the two will be used. Which one is undefined.
Warning: Unknown type 'std::G__CINT_ENDL' in function argument handled as int /usr/local/cint/cint/include/_iostream:10:
Warning: Unknown type 'std::G__CINT_ENDS' in function argument handled as int /usr/local/cint/cint/include/_iostream:12:
Warning: Unknown type 'std::G__CINT_FLUSH' in function argument handled as int /usr/local/cint/cint/include/_iostream:14:
Warning: Unknown type 'std::G__CINT_ws' in function argument handled as int /usr/local/cint/cint/include/_iostream:17:
Warning: Unknown type 'std::G__CINT_WS' in function argument handled as int /usr/local/cint/cint/include/_iostream:19:
Warning: Unknown type 'std::G__CINT_IOFLAGS' in function argument handled as int /usr/local/cint/cint/include/_iostream:23:
Warning: Unknown type 'std::G__CINT_IOFLAGS' in function argument handled as int /usr/local/cint/cint/include/_iostream:27:
Warning: Unknown type 'std::G__CINT_NOSUPPORT' in function argument handled as int /usr/local/cint/cint/include/_iostream:32:
Warning: Unknown type 'std::G__CINT_NOSUPPORT' in function argument handled as int /usr/local/cint/cint/include/_iostream:36:
ERROR:ROOT.TUnixSystem.DispatchSignals] segmentation violation
ERROR:stack] File "/usr/local/bin/ipython", line 9, in <module>
ERROR:stack]   load_entry_point('ipython==4.0.0', 'console_scripts', 'ipython')()
ERROR:stack] File "/Library/Python/2.7/site-packages/ipython-4.0.0-py2.7.egg/IPython/__init__.py", line 118, in start_ipython
ERROR:stack]   return launch_new_instance(argv=argv, **kwargs)
ERROR:stack] File "/Library/Python/2.7/site-packages/traitlets-4.0.0-py2.7.egg/traitlets/config/application.py", line 592, in launch_instance
ERROR:stack]   app.start()
ERROR:stack] File "/Library/Python/2.7/site-packages/ipython-4.0.0-py2.7.egg/IPython/terminal/ipapp.py", line 353, in start
ERROR:stack]   self.shell.mainloop()
ERROR:stack] File "/Library/Python/2.7/site-packages/ipython-4.0.0-py2.7.egg/IPython/terminal/interactiveshell.py", line 381, in mainloop
ERROR:stack]   self.interact(display_banner=display_banner)
ERROR:stack] File "/Library/Python/2.7/site-packages/ipython-4.0.0-py2.7.egg/IPython/terminal/interactiveshell.py", line 505, in interact
ERROR:stack]   self.run_cell(source_raw, store_history=True)
ERROR:stack] File "/Library/Python/2.7/site-packages/ipython-4.0.0-py2.7.egg/IPython/core/interactiveshell.py", line 2902, in run_cell
ERROR:stack]   interactivity=interactivity, compiler=compiler, result=result)
ERROR:stack] File "/Library/Python/2.7/site-packages/ipython-4.0.0-py2.7.egg/IPython/core/interactiveshell.py", line 3006, in run_ast_nodes
ERROR:stack]   if self.run_code(code, result):
ERROR:stack] File "/Library/Python/2.7/site-packages/ipython-4.0.0-py2.7.egg/IPython/core/interactiveshell.py", line 3066, in run_code
ERROR:stack]   exec(code_obj, self.user_global_ns, self.user_ns)
ERROR:stack] File "<ipython-input-1-c688f95e9568>", line 1, in <module>
ERROR:stack]   import rootpy
ERROR:stack] File "/usr/local/lib/python2.7/site-packages/rootpy/__init__.py", line 30, in <module>
ERROR:stack]   from . import defaults
ERROR:stack] File "/Users/larsm/Software/root/lib/ROOT.py", line 352, in _importhook
ERROR:stack]   return _orig_ihook( name, *args, **kwds )
ERROR:stack] File "/usr/local/lib/python2.7/site-packages/rootpy/defaults.py", line 49, in <module>
ERROR:stack]   QROOT.TH1.SetDefaultSumw2(True)
ERROR:stack] File "/usr/local/lib/python2.7/site-packages/rootpy/utils/module_facade.py", line 84, in __getattr__
ERROR:stack]   result = sup.__getattr__(key)
ERROR:stack] File "/usr/local/lib/python2.7/site-packages/rootpy/utils/quickroot.py", line 76, in __getattr__
ERROR:stack]   thing = Quick(symbol)
ERROR:stack] File "<string>", line 1, in <lambda>
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
_ctypes/callbacks.c in 'calling callback function'()

/usr/local/lib/python2.7/site-packages/rootpy/logger/roothandler.pyc in python_logging_error_handler(level, root_says_abort, location, msg)
    107             # We can't raise an exception from here because ctypes/PyROOT swallows it.
    108             # Hence the need for dark magic, we re-raise it within a trace.
--> 109             from .. import ROOTError
    110             raise ROOTError(level, location, msg)
    111         except RuntimeError:

ImportError: cannot import name ROOTError
```

This is on Mac OS X with python 2.7.10.
Has anyone seen this before?

Thanks,
Lars

**Comment by ndawe** [comment]
It looks like you have two competing installations of ROOT on that system: one in /Users/larsm/Software/root_v5.34.34_build/lib and another in /usr/local/lib. If they are not exactly the same version or were not compiled with the same compiler (gcc vs clang), then this could cause nasty problems.

Can you try cleaning one up?

**Comment by lmohrmann** [comment]
Mmh, I just re-installed root and both of the libCore.so files are created during that installation. Nevertheless, I get the above error. However, replacing the file in /usr/local/lib with a symlink to the other one resolves the problem...

Don't know whether this is a problem in ROOT or rootpy...

**Comment by ndawe** [comment]
I'm pretty certain this is just a configuration problem on your system. We've seen things like this happen many times with multiple incompatible installations of ROOT kicking around.
