### ISSUE TITLE
UnboundLocalError: local variable 'hlist' referenced before assignment

### ISSUE THREAD

**Issue by qbuat** [rootpy/rootpy#706]
Hi everyone,

The variable ```hlist``` is not defined in this block: https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/root2matplotlib.py#L451.

I believe that adding the line below should fix this issue:

```python
 hlist = _maybe_reversed(hists, reverse)
```

Here is the traceback for reference:

```bash
Traceback (most recent call last):
  File "/Users/quentin/software/tauperf/sk", line 158, in <module>
    data_test[data_test['is_sig'] == 0]['weight'])
  File "/Users/quentin/software/tauperf/tauperf/plotting/mpl.py", line 45, in score_plot
    rmpl.bar([hsig, hbkg], stacked=False)
  File "/Users/quentin/Library/Python/2.7/lib/python/site-packages/rootpy/plotting/root2matplotlib.py", line 451, in bar
    for h in hlist:
UnboundLocalError: local variable 'hlist' referenced before assignment
```

Cheers,
Quentin

**Comment by ndawe** [comment]
Thanks for reporting this! Fixing now...

**Comment by ndawe** [comment]
Also added coverage of this case in the unit test

**Comment by ndawe** [comment]
Fixed
