### ISSUE TITLE
Setting color/fillcolor at same time causes incorrect error

### ISSUE THREAD

**Issue by kratsg** [rootpy/rootpy#754]
```
{'color': 'red', 'legendstyle': 'f', 'fillcolor': 'red'}
--------------------
An exception was caught!
Traceback (most recent call last):
  File "TakeOverTheWorld/totw.py", line 303, in <module>
    hist.decorate(**hist_styles)
  File "/Users/kratsg/.virtualenvs/TOTW/lib/python2.7/site-packages/rootpy/plotting/base.py", line 194, in decorate
    's' if len(incompatible) != 1 else ''))
IndexError: tuple index out of range
```

https://github.com/rootpy/rootpy/blob/7fea56851620348f35ccaf987a30e63c8d62225f/rootpy/plotting/base.py#L187-L192

**Comment by ndawe** [comment]
That was an easy fix
