### ISSUE TITLE
gDirectory strangeness in ROOT 6.10/02

### ISSUE THREAD

**Issue by ndawe** [rootpy/rootpy#770]
```python
from rootpy.io import root_open

with root_open("test.root", 'recreate') as f:
    pass

with root_open("test.root", 'r') as f:
    pass
```

gives:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/endw/workspace/rootpy/rootpy/logger/roothandler.py", line 98, in python_logging_error_handler
    log.log(lvl, msg)
  File "/usr/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/home/endw/workspace/rootpy/rootpy/logger/extended_logger.py", line 205, in callHandlers
    result = LoggerClass.callHandlers(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 889, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root not opened in write mode
WARNING:ROOT.TFile.Write] file test.root ...
```

**Comment by ndawe** [comment]
Fixed in #771
