### ISSUE TITLE
Can't import rootpy in Python 3.8

### ISSUE THREAD

**Issue by masonproffitt** [rootpy/rootpy#812]
If you try to use rootpy in Python 3.8, this is what happens:

```python
>>> import rootpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gscratch/stf/masonlp/conda/envs/root/lib/python3.8/site-packages/rootpy/__init__.py", line 29, in <module>
    from .logger import log
  File "/gscratch/stf/masonlp/conda/envs/root/lib/python3.8/site-packages/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/gscratch/stf/masonlp/conda/envs/root/lib/python3.8/site-packages/rootpy/logger/__init__.py", line 111, in <module>
    handler.setFormatter(CustomColoredFormatter())
  File "/gscratch/stf/masonlp/conda/envs/root/lib/python3.8/site-packages/rootpy/logger/formatter.py", line 51, in __init__
    CustomFormatter.__init__(self, fmt, datefmt)
  File "/gscratch/stf/masonlp/conda/envs/root/lib/python3.8/site-packages/rootpy/logger/formatter.py", line 40, in __init__
    logging.Formatter.__init__(self, fmt, datefmt)
  File "/gscratch/stf/masonlp/conda/envs/root/lib/python3.8/logging/__init__.py", line 576, in __init__
    self._style.validate()
  File "/gscratch/stf/masonlp/conda/envs/root/lib/python3.8/logging/__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '{color}{levelname}:{name}] {message}' for '%' style
```

This is because `CustomFormatter` calls `logging.Formatter.__init__()` with a `.format()` style string, but the `style` for `Formatter` defaults to `'%'` (see https://docs.python.org/3/library/logging.html#logging.Formatter). `format()` is overridden for the class, which is why everything works in Python versions before 3.8, but 3.8 added a `validate=True` parameter, which verifies that the given string actually follows the expected format. Otherwise it raises an error like above.

**Comment by xaratustrah** [comment]
I also get the same error while importing into python3.8. I am using the latest [rootproject/root-archlinux](https://hub.docker.com/r/rootproject/root-archlinux) docker image.

I tried to use @masonproffitt fix, directly from their [fork](https://github.com/masonproffitt/rootpy/tree/fix_3.8_import) as they described above. The issue with `import rootpy` was solved, but when importing other stuff, such as `from rootpy.plotting import Hist`, I get the following errors:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/rootpy/rootpy/plotting/__init__.py", line 6, in <module>
    from ..utils.hook import classhook, super_overridden
  File "/usr/lib/python3.8/site-packages/ROOT.py", line 522, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/tmp/rootpy/rootpy/utils/hook.py", line 6, in <module>
    from .inject_closure import inject_closure_values
  File "/usr/lib/python3.8/site-packages/ROOT.py", line 522, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/tmp/rootpy/rootpy/utils/inject_closure.py", line 5, in <module>
    from ..extern import byteplay3 as byteplay
  File "/usr/lib/python3.8/site-packages/ROOT.py", line 522, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/tmp/rootpy/rootpy/extern/byteplay3/__init__.py", line 9, in <module>
    from .wbyteplay import *
  File "/usr/lib/python3.8/site-packages/ROOT.py", line 522, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/tmp/rootpy/rootpy/extern/byteplay3/wbyteplay.py", line 93, in <module>
    BREAK_LOOP,
NameError: name 'BREAK_LOOP' is not defined
```

**Comment by sahilyadav27** [comment]
I also faced a similar issue while converting a ROOT file into a hdf5 file using root2hdf5. Were you able to find any solution to this error?

**Comment by xaratustrah** [comment]
@sahilyadav27 No I didn't succeed. Seems to be a more detailed problem. For your application maybe you can check [uproot](https://github.com/scikit-hep/uproot), to read ROOT files and convert them to hdf5 format yourself using [h5py](https://www.h5py.org/).

**Comment by sahilyadav27** [comment]
Thanks for the information @xaratustrah ! I was able to solve this issue by downgrading python to 3.7 since rootpy doesn't work well with 3.8. But there were some other issues while reading tree branches though.

**Comment by benedettosiddi** [comment]
It does not work also in python 3.9
